title: Thathsarani Sandarekha
logo: /assets/images/2.png
description: >
  Machine Learning Engineer | AI Researcher | 
  Computer Vision & LLM Enthusiast | BSc (Hons) AI & Data Science (RGU)
show_downloads: false
theme: jekyll-theme-minimal
